- id: kubeconform-helm
  name: Kubeconform Helm
  description: Run kubeconform for Helm charts
  language: python
  entry: scripts/pre-commit.py
  files: ^(helper-|)charts/[^/]+/(\.kubeconform|\.helmignore|templates/NOTES.txt|.*\.(ya?ml|json|tpl))$
  require_serial: true
